### ISSUE TITLE
Is size needed

### ISSUE THREAD

**Issue by hoseyjoe** [gskinner/SPL#1]
SPL / source / com / gskinner / text / TextUtils.as
Line 65 is checking for the height/width of the found textfield object.  I was getting errors because my autosizing field was still 0x0 and it was not being found by this utility.  Also it appears that by looping through it a textfield found after a larger field was may not be found (with same parent) as the size is reset from 0 to the larger height/width.  

Anyways removing the local variable size seems to be fine.  Any input on why it would be needed?
Thanks

**Comment by wdamien** [comment]
It was initially needed because in some cases we would search pretty far up the tree to find a TextField, having a size check was just a good fail safe to ensure we were binding to a valid TextField. It's best practice to bind the spelling highlighter to a single component with a single TextField (or just directly to the TextField). So the case of having multiple TextField's in a single component is rare.
